parserOptions:
    ecmaVersion: 6
    sourceType: module
env:
    node: true
extends: eslint:recommended
globals:
    Promise: false
rules:
    no-console: off
    no-unused-vars:
        - error
        - 
            args: none
    require-yield: off
    no-case-declarations: off
    no-inner-declarations: off
    no-cond-assign: off
    no-irregular-whitespace:
        - error
        -
            skipRegExps: true
    semi:
        - error
        - never
    keyword-spacing:
        - error
        -
            before: true
            after: true
    space-before-blocks:
        - error
        - always
    no-multi-spaces:
        - error
        -
            exceptions:
                Property: true
                VariableDeclarator: true
                ImportDeclaration: true
    no-trailing-spaces:
        - error
        -
            skipBlankLines: true
    no-whitespace-before-property: error
    spaced-comment:
        - error
        - always
    unicode-bom:
        - error
        - never
    yield-star-spacing:
        - error
