language: node_js
node_js:
    - "7.0.0"
    - "7.4.0"
cache:
    directories:
        - node_modules/
services:
    - mongodb
script:
    - npm run lint
    - npm run docs-check
    - npm run migrate