language: python
python:
    - "3.6"
node_js:
    - "7.4.0"
services:
    - mongodb
    - redis-server
script:
    - .ci-files/setup-api-server.sh
    - cp .ci_files/web.json config/
    - pip3 install flask pyjade requests
    - forever start -c "python3"
